// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlH22aIzKhfC2B8Nw9mPQZjbw-4LHO7Rc',
    appId: '1:307731463085:web:62573453c48af7238d3f24',
    messagingSenderId: '307731463085',
    projectId: 'instagram-clone-4ffa5',
    authDomain: 'instagram-clone-4ffa5.firebaseapp.com',
    storageBucket: 'instagram-clone-4ffa5.appspot.com',
    measurementId: 'G-TFWVEDC4CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtm5Oe7j-ciOM0OD9QAf6U5DQ2ZIS4_uA',
    appId: '1:307731463085:android:4812e04f74d0f57c8d3f24',
    messagingSenderId: '307731463085',
    projectId: 'instagram-clone-4ffa5',
    storageBucket: 'instagram-clone-4ffa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdP3NLRIrXTEGo20DiqGgRcRMIrG1UGyk',
    appId: '1:307731463085:ios:6158b2668ef9bccd8d3f24',
    messagingSenderId: '307731463085',
    projectId: 'instagram-clone-4ffa5',
    storageBucket: 'instagram-clone-4ffa5.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdP3NLRIrXTEGo20DiqGgRcRMIrG1UGyk',
    appId: '1:307731463085:ios:6158b2668ef9bccd8d3f24',
    messagingSenderId: '307731463085',
    projectId: 'instagram-clone-4ffa5',
    storageBucket: 'instagram-clone-4ffa5.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlH22aIzKhfC2B8Nw9mPQZjbw-4LHO7Rc',
    appId: '1:307731463085:web:aea0fb104bd5db2b8d3f24',
    messagingSenderId: '307731463085',
    projectId: 'instagram-clone-4ffa5',
    authDomain: 'instagram-clone-4ffa5.firebaseapp.com',
    storageBucket: 'instagram-clone-4ffa5.appspot.com',
    measurementId: 'G-2T14XCKTPF',
  );
}
